myproj/authentication/urls.py
from django.urls import path, include
from . import views

app_name  = 'authentication'

urlpatterns = [
   
    path('', views.index , name='index'),
    path('signup/', views.signup , name='signup'),
    path('login/', views.login , name='login'),
    path('logout/', views.logout , name='logout'),
]

myproj/myproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("authentication.urls")),
]

myproj/authentication/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth import authenticate, login





def index(request):
    return render (request, "index.html")


def signup(request):
    if request.method == 'POST':
        u_name = request.POST.get('username') 
        mail = request.POST.get('email')
        pass1 = request.POST.get('password1')
        pass2 = request.POST.get('password2')
        
        if u_name and mail and pass1 and pass2:
            if pass1 == pass2:
                if User.objects.filter(username=u_name).exists(): 
                    return redirect('authentication:signup')
                else:
                    user = User.objects.create_user(username=u_name, email=mail, password=pass1)
                    user.save()
                    return redirect('authentication:login')
            else:
                return redirect('authentication:signup')
        else:
            return redirect('authentication:signup')
    else:                
        return render(request, "signup.html")


from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login


def login(request):
    if request.method == 'POST':
        u_name = request.POST.get('username')
        pass1 = request.POST.get('password')
        
        user = authenticate(request, username=u_name, password=pass1)
        
        if user is not None:
            auth_login(request, user)
            return redirect('authentication:index')
        else:
            return redirect('authentication:login')
        
    else:
        return render(request, "login.html")




def logout(request):
    auth.logout(request)
    return redirect('authentication:index')

myproj/templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    {% block link %}{% endblock link %}

  </head>
  <body>
    {% include "navbar.html" %}
    {% block content %}{% endblock content %}



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

    {% block script %}{% endblock script %}

  </body>
</html>

myproj/templates/index.html
{% extends "base.html" %}
{% load static %}





    {% block link %}
    
    
    
    
    {% endblock link %}







    {% block content %}

   
    {% endblock content %}







  
    {% block script %}

    
    {% endblock script %}

myproj/templates/login.html
{% extends "base.html" %}
{% load static %}

    {% block link %}
    
    <style>
        body{
            background: color #f8f8f8;
        }
        .container{
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .card{
            padding: 2rem;
            border-radius: 0.5rem;
            box-shadow: 0 4px 8px rgba(0, 0, 0,0.1);
            width: 25rem;
        }
    </style>

    {% endblock link %}



    {% block content %}
    
    <div class="container">

        <div class="card">
            <h3 class="card-title text-center text-primary" >Login</h3>
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group pt-5">
                    <input class="form-control" type="text" name="username" id="username" placeholder="username" required>
                </div>
            
                <div class="form-group pt-3">              
                    <input class="form-control" type="password" name="password" id="password" placeholder="password" required>
                </div>
            
                <div class="form-group pt-5 text-center">
                    <input class="btn btn-primary text-center px-5" type="submit">
                </div>
            </form>
            
        </div>
    </div>
    
    {% endblock content %}



    {% block script %}{% endblock script %}
    

myproj/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand h1 px-5" href="{% url "authentication:index" %}">VN SHOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 px-5">
        <li class="nav-item me-2">
          <a class="nav-link active" aria-current="page" href="{% url "authentication:index" %}">Home</a>
        </li>
        <li class="nav-item me-2">
          <a class="nav-link" href="#">Profile</a>
        </li>
        <li class="nav-item me-2">
          <a class="nav-link" href="{% url "authentication:signup" %}">Signup</a>
        </li>
        <li class="nav-item me-2">
          <a class="nav-link" href="{% url "authentication:login" %}">Login</a>
        </li>
        <li class="nav-item me-2">
          <a class="nav-link" href="{% url "authentication:logout" %}">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

myproj/templates/signup.html
{% extends "base.html" %}
{% load static %}

    {% block link %}
    
    <style>
        body{
            background: color #f8f8f8;
        }
        .container{
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .card{
            padding: 2rem;
            border-radius: 0.5rem;
            box-shadow: 0 4px 8px rgba(0, 0, 0,0.1);
            width: 30rem;
        }
    </style>

    {% endblock link %}



    {% block content %}
    
    <div class="container">

        <div class="card">
            <h3 class="card-title text-center text-primary" >Sign Up</h3>
            <form method="post">
                {% csrf_token %}
                <div class="form-group pt-5">
                    <input class="form-control" type="text" name="username" id="username" placeholder="username" required>
                </div>
                <div class="form-group pt-3">
                    <input class="form-control" type="email" name="email" id="email" placeholder="email" required>
                </div>
                <div class="form-group pt-3">              
                    <input class="form-control" type="password" name="password1" id="password1" placeholder="password" required>
                </div>
                <div class="form-group pt-3">
                    <input class="form-control" type="password" name="password2" id="password2" placeholder="confirm password"required>
                </div>
                <div class="form-group pt-5 text-center">
                    <input class="btn btn-primary text-center px-5" type="submit">
                </div>
            </form>
            
        </div>
    </div>
    
    {% endblock content %}



    {% block script %}{% endblock script %}
    